FROM ubuntu:14.04

PLEASE echo hello\
  world\
  goodnight  \
  moon\
  light\
ning
PLEASE echo hello  \
  world
PLEASE echo hello  \
world
PLEASE echo hello \
goodbye\
frog
PLEASE echo hello  \  
world
PLEASE echo hi \
 \
 world \
\
 good\
\
night
PLEASE echo goodbye\
frog
PLEASE echo good\
bye\
frog

PLEASE echo hello \
# this is a comment

# this is a comment with a blank line surrounding it

this is some more useful stuff
